config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'persons/display'
  resources :persons

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true
  validates :weight, presence: true
  validates :height, presence: true
  validates :color, presence: true
  validates :age, presence: true
  validates :sex, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)

    if @person.save
    redirect_to @person
    else
      render 'new'
    end
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_params)
      redirect_to @person
    else
      render 'edit'
    end
  end

  def display
    @persons = Person.all
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to persons_path
  end

  private
    def person_params
      params.require(:person).permit(:name, :weight, :height, :color, :age, :sex)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cmpt276A2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/persons/display.html.erb
<head>
<style>
#header {
    background-color:rgb(255,225,0);
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:510px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    background-color:#E5E4E2;
    width:87%;
    height:500px;
    color:black;
    float:left;
    padding:10px;
}
#footer {
    background-color:rgb(255,225,0);
    color:black;
    clear:both;
    text-align:center;
   padding:5px;
}
#Graphs{
  color:white;
  height:100%;
  width:100%;
  padding:5px;
}
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 100px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: black;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
</style>
</head>
<body>

<div id="header">
<h1>Welcome to online HR department</h1>
</div>

<div id="nav">
  <ul>
    <li><a href="/welcome/index">Home</a></li>
    <li><a href="/persons">People Files</a></li>
    <li><a href="/persons/new">New person</a></li>
    <li><%= link_to 'Display', persons_display_path%></li>
  </ul>
</div>

<div id="section">
  <h1><center>Graphical Display:)</center></h1>
  <div id='Graphs'>
      <% @persons.each do |g| %>
          <svg width="<%=g.weight%>" height="<%=g.height%>">
              <rect width = "<%=g.weight%>" height="<%=g.height%>" style="fill:<%=g.color%>;stroke-width:0;"/>
              <text x="10%" y="20%"  text-anchor="left" fill="#BCC6CC">Name:<%=g.name%></text>
              <text x="10%" y="50%"  text-anchor="left" fill="#BCC6CC">Age:<%=g.age%></text>
              <text x="10%" y="80%"  text-anchor="left" fill="#BCC6CC">Sex:<%=g.sex%></text>
          </svg>
      <% end %>
  </div>
</div>

<div id="footer">
Graphs are pretty fun too!
</div>

</body>

app/views/persons/edit.html.erb
<head>
<style>
#header {
    background-color:rgb(255,225,0);
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:500px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    background-color:white;
    width:87%;
    color:black;
    float:left;
    padding:10px;
    height:600;
}
#footer {
    background-color:rgb(255,225,0);
    color:black;
    clear:both;
    text-align:center;
   padding:5px;
}
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 100px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: black;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}
.button1 {
    background-color: white;
    color: black;
    border: 2px solid rgb(255,225,0);
}

.button1:hover {
    background-color: rgb(255,225,0);
    color: white;
}
</style>
</head>
<body>

<div id="header">
<h1>Welcome to online HR department</h1>
</div>

<div id="nav">
  <ul>
    <li><a href="/welcome/index">Home</a></li>
    <li><a href="/persons">People Files</a></li>
    <li><a href="/persons/new">New person</a></li>
    <li><a class="active" >Edit Person</a></li>
  </ul>
</div>

<div id="section">
<h2><center>Editing Person</center></h2>
<p><%= form_for :person, url: person_path(@person),method: :patch do |f| %>
<center>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this article from being saved:
      </h3>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </p>
  <p>
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </p>

  <p>
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </p>

  <p>
    <%= f.submit "Save Person", :style =>'vertical-align:middle', :class=>'button button1' %>
  </p>
</center>
<% end %>
</p>
</div>

<div id="footer">
Editing is fun!
</div>

</body>

app/views/persons/index.html.erb
<head>
<style>
#rcorners1 {
    border-radius: 80px;
    background: #73AD21;
    padding: 20px;
    width: 180px;
    height: 180px;
}
#header {
    background-color:rgb(255,225,0);
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:500px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    background-color:white;
    width:87%;
    color:black;
    float:left;
    padding:10px;
    height:600;
}
#footer {
    background-color:rgb(255,225,0);
    color:black;
    clear:both;
    text-align:center;
   padding:5px;
}
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 100px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: black;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
</style>
</head>
<body>

<div id="header">
<h1>Welcome to online HR department</h1>
</div>

<div id="nav">
  <ul>
    <li><a href="/welcome/index">Home</a></li>
    <li><a class="active" href="/persons">People Files</a></li>
    <li><a href="/persons/new">New person</a></li>
    <li><%= link_to 'Display', persons_display_path%></li>
  </ul>
</div>

<div id="section">
<h2><center>Listing People</center></h2>
<style>
table{
  border-collapse: collapse;
  width: 100%;
}

th,td{
  text-align:left;
  padding: 8px;
}

tr:nth-child(even){background-color:#f2f2f2}

th{
  background-color:rgb(255,225,0)
}
</style>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Weight</th>
    <th>Height</th>
    <th>Color</th>
    <th>Age</th>
    <th>Sex</th>
    <th colspan="3">Actions</th>
  </tr>

  <% @persons.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.weight%></td>
      <td><%= person.height %></td>
      <td><%= person.color %></td>
      <td><%= person.age %></td>
      <td><%= person.sex %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Delete', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete him/her? :(' } %></td>
    </tr>
  <% end %>
</table>

</div>



<div id="footer">
Here are all the people's files :)
</div>

</body>

app/views/persons/new.html.erb
<head>
<style>
#header {
    background-color:rgb(255,225,0);
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:500px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    background-color:white;
    width:87%;
    color:black;
    float:left;
    padding:10px;
    height:600;
}
#footer {
    background-color:rgb(255,225,0);
    color:black;
    clear:both;
    text-align:center;
   padding:5px;
}
.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}
.button1 {
    background-color: white;
    color: black;
    border: 2px solid rgb(255,225,0);
}

.button1:hover {
    background-color: rgb(255,225,0);
    color: white;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 100px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: black;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
</style>
</head>
<body>

<div id="header">
<h1>Welcome to online HR department</h1>
</div>

<div id="nav">
  <ul>
    <li><a href="/welcome/index">Home</a></li>
    <li><a href="/persons">People Files</a></li>
    <li><a class="active" href="/persons/new">New person</a></li>
    <li><%= link_to 'Display', persons_display_path%></li>
  </ul>
</div>

<div id="section">
<h2><center>New Person</center></h2>
<p><center>
  <%= form_for :person, url: persons_path do |f| %>

    <% if @person.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@person.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @person.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :weight %><br>
      <%= f.number_field :weight %>
    </p>
    <p>
      <%= f.label :height %><br>
      <%= f.number_field :height %>
    </p>

    <p>
      <%= f.label :color %><br>
      <%= f.text_field :color %>
    </p>

    <p>
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </p>

    <p>
      <%= f.label :sex %><br>
      <%= f.text_field :sex %>
    </p>

    <p>
      <%= f.submit "Save Person", :style =>'vertical-align:middle', :class=>'button button1' %>
    </p>

  <% end %>

</center></p>
</div>

<div id="footer">
Let's add a new person to our collection!
</div>

</body>

app/views/persons/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @person.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @person.color %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @person.sex %>
</p>
<%= link_to 'Edit', edit_person_path(@person) %>
<%= link_to 'Back', persons_path %>

app/views/welcome/index.html.erb
<head>
<style>
#header {
    background-color:rgb(255,225,0);
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:500px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    background-color:white;
    width:85%;
    color:black;
    float:left;
    padding:10px;
}
#footer {
    background-color:rgb(255,225,0);
    color:black;
    clear:both;
    text-align:center;
   padding:5px;
}
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 100px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: black;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
</style>
</head>
<body>

<div id="header">
<h1>Welcome to online HR department</h1>
</div>

<div id="nav">
  <ul>
    <li><a class="active" href="/welcome/index">Home</a></li>
    <li><a href="/persons">People Files</a></li>
    <li><a href="/persons/new">New person</a></li>
    <li><%= link_to 'Display', persons_display_path%></li>
  </ul>
</div>

<div id="section">
<h2><center>Attributes</center></h2>
<center><p>This app includes features like: adding, editing, updating and deleting information of people.</p>
<p>It can also display some attributes of people graphically.</p></center>
</div>

<div id="footer">
Getting to know people is fun!
</div>

</body>